// Generated by CoffeeScript 1.7.1
(function() {
  var Api, qs, request;

  request = require('./prequest');

  qs = require('querystring');

  Api = (function() {
    function Api(key) {
      this.key = key;
      this.base = 'http://api.justyo.co';
    }

    Api.prototype.subscribers = function() {
      return this.get('/subscribers');
    };

    Api.prototype.yoOne = function(username) {
      return this.post('/yo', {
        username: username
      });
    };

    Api.prototype.yoAll = function() {
      return this.post('/yoall', {});
    };

    Api.prototype.route = function(path) {
      return this.base + path;
    };

    Api.prototype.get = function(path) {
      var url;
      url = "" + (this.route(path)) + "/?api_token=" + this.key;
      return request(url);
    };

    Api.prototype.post = function(path, data) {
      var opts;
      data.api_token = this.key;
      opts = {
        url: this.route(path) + '/',
        method: 'POST',
        form: qs.stringify(data)
      };
      return request(opts);
    };

    return Api;

  })();

  module.exports = Api;

}).call(this);
